version: "3.3"
name: track-price-changes
services:
    flask:
        image: maie421/track-price-changes-flask:latest
        container_name: flask
        restart: unless-stopped
        expose:
            - 5000

    nginx:
        image: maie421/track-price-changes-nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"