name: 서비스 배포

on:
  push:
#    paths:
#      - 'web/**'
    branches: ['master', 'nginx']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t track-price-changes-flask:latest ./web
          docker build -t track-price-changes-nginx:latest ./nginx
          docker tag track-price-changes-flask ${{ secrets.DOCKER_USERNAME }}/track-price-changes-flask:latest
          docker tag track-price-changes-nginx ${{ secrets.DOCKER_USERNAME }}/track-price-changes-nginx:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/track-price-changes-flask:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/track-price-changes-nginx:latest

      - name: Deploy to track-price-changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PUBLIC_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/track-price-changes-flask:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/track-price-changes-nginx:latest
            docker-compose -f /home/ubuntu/deploy/docker-compose-dev.yml up -d