name: 크롤링 배치

on:
  schedule:
    - cron: '0 */24 * * *' # 24마다 시간 실행
  workflow_dispatch:

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libffi-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r crawling/requirements.txt

      - name: Run Python script
        run: python3 crawling/coupang/getProducts.py ${{ secrets.DB_CRAWLING_IP }} ${{ secrets.DB_CRAWLING_USER }} ${{ secrets.DB_CRAWLING_PASSWORD }}